import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(__dirname, '..')

async function readFile(relPath) {
  return fs.readFile(path.join(repoRoot, relPath), 'utf8')
}

test('question metadata should expose flow profile routing context fields', async () => {
  const src = await readFile('types/question.ts')
  assert.ok(src.includes('flowContext?: {'))
  assert.ok(src.includes('region?: string'))
  assert.ok(src.includes('scene?: string'))
  assert.ok(src.includes('grade?: string'))
})

test('listening-choice binding should derive routing context from opts + metadata', async () => {
  const src = await readFile('engine/flow/listening-choice/binding.ts')

  assert.ok(src.includes('function resolveRoutingCtx('))
  assert.ok(src.includes('flowContext'))
  assert.ok(src.includes('resolveRoutingCtx(question, opts?.ctx)'))
  assert.ok(src.includes('resolveStandardModule(question, source, routingCtx)'))
  assert.ok(src.includes('resolveStandardModule(resolvedQuestion, src, routingCtx)'))
  assert.ok(src.includes('const hasRoutingCtx = Boolean('))
  assert.ok(src.includes('prefer profile routing over stale source refs'))
  const ctxBlock = src.indexOf('if (hasRoutingCtx)')
  const explicitBlock = src.indexOf('if (explicitId && explicitVersion > 0)')
  assert.ok(ctxBlock > -1 && explicitBlock > -1 && ctxBlock < explicitBlock, 'Expected routing ctx branch before explicit source branch')
})

test('listening-choice normalization should no longer auto-write flow library on save fallback', async () => {
  const src = await readFile('engine/flow/listening-choice/binding.ts')
  assert.ok(!src.includes('flowLibrary.ensureModule('))
  assert.ok(src.includes('FLOW_NORMALIZATION_ISSUE_CODE'))
  assert.ok(src.includes('withFlowNormalizationIssue'))
  assert.ok(src.includes('请先到「题型流程」修正流程线后再保存题目'))
})

test('flow center copy should use the new "题型流程" terminology', async () => {
  const src = await readFile('components/views/FlowModulesManager.vue')

  assert.ok(src.includes('更新当前流程线'))
  assert.ok(src.includes('题型流程图'))
  assert.ok(!src.includes('题型流程库 (自动沉淀)'))
  assert.ok(!src.includes('流程 ID：'))
  assert.ok(!src.includes('新流程线 ID（可选）'))
  assert.ok(!src.includes('模块 ID'))
  assert.ok(!src.includes('保存流程模板'))
})

test('flow center should provide region-binding checklist in listening-choice flow page', async () => {
  const src = await readFile('components/views/FlowModulesManager.vue')

  assert.ok(src.includes('地区匹配'))
  assert.ok(src.includes('一个流程线可绑定多个地区；一个地区只能绑定 1 个流程线'))
  assert.ok(src.includes("const REGION_GENERAL_LABEL = '通用'"))
  assert.ok(src.includes('听后选择通用流程'))
  assert.ok(src.includes('「通用」就是默认/标准流程'))
  assert.ok(src.includes('toggleRegionBindingForCurrentFlowLine'))
  assert.ok(src.includes('formatRegionBindingTarget'))
  assert.ok(!src.includes('题型流程路由'))
})

test('flow center should support flow-line switching and wizard-based create/publish', async () => {
  const src = await readFile('components/views/FlowModulesManager.vue')
  assert.ok(src.includes('流程线切换'))
  assert.ok(src.includes('新建流程线（向导）'))
  assert.ok(src.includes('flowLineWizardVisible'))
  assert.ok(src.includes('openFlowLineCreateWizard'))
  assert.ok(src.includes('confirmCreateFlowLineFromWizard'))
  assert.ok(src.includes('创建并发布'))
  assert.ok(src.includes('switchToFlowLine'))
})

test('flow center should remove onboarding guide and route presets from flow page', async () => {
  const src = await readFile('components/views/FlowModulesManager.vue')
  assert.ok(!src.includes('编辑上手引导'))
  assert.ok(!src.includes('setOnboardingStage'))
  assert.ok(!src.includes('runOnboardingAction'))
  assert.ok(!src.includes('applyRoutePreset'))
  assert.ok(!src.includes('地区+场景示例'))
})

test('flow profile store should support removing profile rules via diagnostics-safe API', async () => {
  const src = await readFile('stores/flowProfiles.ts')
  assert.ok(src.includes('removeWithDiagnostics(id: string)'))
  assert.ok(!src.includes('remove(id: string)'))
  assert.ok(src.includes('this.state.profiles = next'))
})

test('flow profile domain usecase should provide scoring, diagnostics and submit validation', async () => {
  const src = await readFile('domain/flow-profile/usecases/scoreProfiles.ts')
  assert.ok(src.includes('export function scoreProfiles('))
  assert.ok(src.includes('export function diagnoseFlowProfileRules('))
  assert.ok(src.includes('export function buildFlowProfileFixSuggestions('))
  assert.ok(src.includes('export function canSubmitFlowProfiles('))
  assert.ok(src.includes('FLOW_REGION_GENERIC_LABEL'))
  assert.ok(src.includes('regionDimScore'))
  assert.ok(src.includes('weakCoverage'))
})

test('flow profile store should support diagnostic-gated submit helpers', async () => {
  const src = await readFile('stores/flowProfiles.ts')
  assert.ok(src.includes('upsertWithDiagnostics(profileInput: unknown)'))
  assert.ok(src.includes('removeWithDiagnostics(id: string)'))
  assert.ok(src.includes('validateBeforeSubmit(questionType: QuestionType)'))
  assert.ok(src.includes('canSubmitFlowProfiles('))
  assert.ok(src.includes('scoreProfiles('))
  assert.ok(src.includes('replaceQuestionTypeProfiles(questionType: QuestionType, profileInputs: unknown[])'))
})

test('flow center should enforce one-region-one-flow via canonical binding replacement', async () => {
  const src = await readFile('components/views/FlowModulesManager.vue')
  assert.ok(src.includes('collectRegionRoutingBindings'))
  assert.ok(src.includes('buildRegionOnlyProfiles'))
  assert.ok(src.includes('replaceRegionRoutingBindings'))
  assert.ok(src.includes("flowProfiles.replaceQuestionTypeProfiles('listening_choice', nextProfiles)"))
})

test('flow center should treat 通用 as default profile binding instead of region rule', async () => {
  const src = await readFile('components/views/FlowModulesManager.vue')
  assert.ok(src.includes('if (isGeneralRegion(region)) return'))
  assert.ok(src.includes('defaultRoutingModuleRef'))
  assert.ok(src.includes('defaultModuleRef: targetModuleRef'))
  assert.ok(src.includes('defaultNote: currentlyBound ? \'听后选择默认流程\' : \'听后选择通用流程\''))
  assert.ok(src.includes('const hasGeneralRegion = regions.some((region) => isGeneralRegion(region))'))
})

test('route simulator util should support loading context from current question metadata', async () => {
  const sim = await readFile('components/views/flow-modules/useRouteSimulator.ts')
  assert.ok(sim.includes('loadRouteSimFromCurrentQuestion'))
  assert.ok(sim.includes('readQuestionFlowContext(data)'))
})

test('route simulator util should support writing context back to current question metadata', async () => {
  const sim = await readFile('components/views/flow-modules/useRouteSimulator.ts')
  assert.ok(sim.includes('syncRouteSimToCurrentQuestion'))
  assert.ok(sim.includes('patchQuestionFlowContext'))
  assert.ok(sim.includes('persistCurrentQuestion(next)'))
})

test('editor workspace should display route matching summary without editable flow context bar', async () => {
  const src = await readFile('components/views/EditorWorkspace.vue')
  assert.ok(src.includes('匹配规则'))
  assert.ok(src.includes('flow-route-hint'))
  assert.ok(src.includes('flowRouteRegionLabel'))
  assert.ok(src.includes('flowRouteResolutionHint'))
  assert.ok(src.includes('地区'))
  assert.ok(!src.includes('流程上下文'))
  assert.ok(!src.includes('function updateFlowContext('))
})

test('side navigation should derive question region metadata from selected 地区 tags', async () => {
  const src = await readFile('components/layout/SideNavigation.vue')
  const draftSrc = await readFile('stores/questionDraft.ts')
  assert.ok(src.includes("const SINGLE_ROOTS = new Set(['教材版本', '学期', '年级', '年份', '难度', '地区'])"))
  assert.ok(src.includes('resolveRegionFromTags(tags)'))
  assert.ok(src.includes('tagStore.getRootCategory(id) !== \'地区\''))
  assert.ok(src.includes('questionDraft.updateMetadata({'))
  assert.ok(src.includes('region'))
  assert.ok(draftSrc.includes('updateMetadata(patch: { tags?: string[]; source?: string; region?: string })'))
  assert.ok(draftSrc.includes('current.metadata.flowContext'))
  assert.ok(!draftSrc.includes('current.metadata.region'))
})

test('editor workspace should map 听说-听后选择 to listening_choice template', async () => {
  const src = await readFile('components/views/EditorWorkspace.vue')
  assert.ok(src.includes("if (leaf === '听后选择') return { templateKey: 'listening_choice', enabled: true, reason: '' }"))
  assert.ok(!src.includes("if (leaf === '听后选择') return { templateKey: 'speaking_hear_choice', enabled: true, reason: '' }"))
})

test('editor workspace should map 听说-听后回答 to speaking_hear_answer template', async () => {
  const src = await readFile('components/views/EditorWorkspace.vue')
  assert.ok(src.includes("if (leaf === '听后回答') return { templateKey: 'speaking_hear_answer', enabled: true, reason: '' }"))
  assert.ok(!src.includes("if (leaf === '听后回答') return { templateKey: 'speaking_steps', enabled: false"))
})

test('question templates should expose speaking_hear_answer creation entry', async () => {
  const src = await readFile('templates/index.ts')
  assert.ok(src.includes('export function createListeningHearAnswerTemplate('))
  assert.ok(src.includes("name: '听后回答'"))
  assert.ok(src.includes("type: 'listening_choice'"))
  assert.ok(src.includes("questionVariant: 'hear_answer'"))
  assert.ok(src.includes('LISTENING_HEAR_ANSWER_STANDARD_FLOW_ID'))
  assert.ok(src.includes("id: LISTENING_HEAR_ANSWER_STANDARD_FLOW_ID"))
  assert.ok(src.includes('create: createListeningHearAnswerTemplate'))
})

test('speaking hear-answer default content should use single-group + double-group baseline', async () => {
  const src = await readFile('stores/contentTemplates.ts')
  assert.ok(src.includes("id: 'tpl_ha_g_1'"))
  assert.ok(src.includes("id: 'tpl_ha_g_2'"))
  assert.ok(src.includes('回答第4-5小题'))
  assert.ok(src.includes("order: 1"))
  assert.ok(src.includes("order: 4"))
  assert.ok(src.includes("order: 5"))
})

test('content template store should keep hear-answer baseline without legacy migration helpers', async () => {
  const src = await readFile('stores/contentTemplates.ts')
  assert.ok(src.includes('DEFAULT_SPEAKING_HEAR_ANSWER_CONTENT_TEMPLATE'))
  assert.ok(src.includes('normalizeSpeakingHearAnswerContentTemplate'))
  assert.ok(!src.includes('isLegacySpeakingHearAnswerDefaultTemplate'))
  assert.ok(!src.includes('isLegacySpeakingHearAnswerExpandedDefaultTemplate'))
})

test('listening-choice binding should use dedicated standard flow for hear-answer variant', async () => {
  const src = await readFile('engine/flow/listening-choice/binding.ts')
  assert.ok(src.includes('LISTENING_HEAR_ANSWER_STANDARD_FLOW_ID'))
  assert.ok(src.includes('function isHearAnswerVariant('))
  assert.ok(src.includes('if (isHearAnswerVariant(question)) {'))
  assert.ok(src.includes("flowModules.getListeningChoiceLatestPublished(LISTENING_HEAR_ANSWER_STANDARD_FLOW_ID)"))
  assert.ok(src.includes('return { module: buildDefaultStandardModule(defaultModuleId), profileId: profileId || matchedProfile?.id }'))
  assert.ok(!src.includes('const migratedId ='))
})

test('flow center should keep region-routing mode handling without legacy auto-migration', async () => {
  const src = await readFile('components/views/FlowModulesManager.vue')
  assert.ok(src.includes('ensureRegionRoutingMode'))
  assert.ok(src.includes('if (!isRegionRoutingEnabled.value) return true'))
  assert.ok(!src.includes('isLegacyRegionRoutingModel'))
  assert.ok(!src.includes('已切换为地区匹配模式'))
})

test('flow center should show region binding target summary per chip', async () => {
  const src = await readFile('components/views/FlowModulesManager.vue')
  assert.ok(src.includes('region-chip__target'))
  assert.ok(src.includes('function formatRegionBindingTarget('))
  assert.ok(src.includes('defaultRoutingModuleRef'))
  assert.ok(src.includes('if (!binding) return `通用：${formatModuleDisplayRef(defaultRoutingModuleRef.value)}`'))
  assert.ok(src.includes("if (isRegionBoundToCurrentFlowLine(region)) return '当前流程线'"))
})

test('flow center should keep runtime trace hooks even without routing panel UI', async () => {
  const src = await readFile('components/views/FlowModulesManager.vue')
  assert.ok(src.includes('flowCenterTraceEvents'))
  assert.ok(src.includes('runtimeDebug.record(flowCenterDebugSessionId'))
  assert.ok(src.includes('exportFlowCenterDiagnostics'))
  assert.ok(src.includes('clearFlowCenterDiagnosticsTrace'))
})

test('flow center should provide read-only visual graph modal from steps', async () => {
  const src = await readFile('components/views/FlowModulesManager.vue')
  const visualSrc = await readFile('components/views/flow-modules/useReadonlyFlowGraph.ts')
  const editableSrc = await readFile('components/views/flow-modules/useEditableFlowGraph.ts')
  const visualCanvasSrc = await readFile('components/editor/flow-visual/ReadonlyFlowCanvas.vue')
  const stencilSrc = await readFile('components/editor/flow-visual/StencilPanel.vue')
  const propertySrc = await readFile('components/editor/flow-visual/PropertyPanel.vue')
  const stepNodeSrc = await readFile('components/editor/flow-visual/StepFlowNode.vue')
  const compileSrc = await readFile('domain/flow-visual/usecases/compileGraphToSteps.ts')
  const mapperSrc = await readFile('domain/flow-visual/usecases/buildListeningChoiceModuleFromLinearSteps.ts')
  const typeSrc = await readFile('types/flow-visual.ts')
  assert.ok(src.includes('查看流程图'))
  assert.ok(src.includes('线性流程可视新建'))
  assert.ok(src.includes('openReadonlyFlowVisual'))
  assert.ok(src.includes('readonlyFlowVisualActiveNode'))
  assert.ok(src.includes('ReadonlyFlowCanvas'))
  assert.ok(src.includes('useEditableFlowGraph'))
  assert.ok(src.includes('StencilPanel'))
  assert.ok(src.includes('PropertyPanel'))
  assert.ok(visualSrc.includes('buildListeningChoiceReadonlyFlowGraph'))
  assert.ok(editableSrc.includes('useEditableFlowGraph'))
  assert.ok(editableSrc.includes('stencilItems'))
  assert.ok(editableSrc.includes('compileResult'))
  assert.ok(editableSrc.includes('buildPropertyFieldsByStepKind'))
  assert.ok(editableSrc.includes('propertyFieldsForSelectedNode'))
  assert.ok(visualSrc.includes('categoryLabel'))
  assert.ok(visualCanvasSrc.includes('readonly-flow-canvas__legend'))
  assert.ok(visualCanvasSrc.includes('reorder-node'))
  assert.ok(visualCanvasSrc.includes('insert-stencil-near-node'))
  assert.ok(visualCanvasSrc.includes('onNodeDrop'))
  assert.ok(visualCanvasSrc.includes('dropTarget?.nodeId'))
  assert.ok(visualCanvasSrc.includes('recentlyMovedNodeId'))
  assert.ok(visualCanvasSrc.includes('onPointerDragStart'))
  assert.ok(visualCanvasSrc.includes('onPointerDragDrop'))
  assert.ok(visualCanvasSrc.includes('pointer-drag-start'))
  assert.ok(visualCanvasSrc.includes('preview-from-node'))
  assert.ok(visualCanvasSrc.includes('从此步预览'))
  assert.ok(visualCanvasSrc.includes('onNodeContextMenu'))
  assert.ok(stencilSrc.includes('元件库'))
  assert.ok(stencilSrc.includes('emit(\'add\', item.kind)'))
  assert.ok(stencilSrc.includes('draggable="true"'))
  assert.ok(stencilSrc.includes('emit(\'drag-start\', kind)'))
  assert.ok(stencilSrc.includes('emit(\'drag-end\')'))
  assert.ok(propertySrc.includes('属性面板'))
  assert.ok(propertySrc.includes('patchField'))
  assert.ok(propertySrc.includes('emit(\'patch\', { autoNext: value })'))
  assert.ok(propertySrc.includes('v-for="field in fields"'))
  assert.ok(propertySrc.includes('Delete 删除'))
  assert.ok(propertySrc.includes('Ctrl/Cmd+Z 撤销'))
  assert.ok(propertySrc.includes('<slot name="bulk" />'))
  assert.ok(stepNodeSrc.includes('BaseFlowNode'))
  assert.ok(stepNodeSrc.includes('drop-on-node'))
  assert.ok(stepNodeSrc.includes('flowKind'))
  assert.ok(stepNodeSrc.includes('reorderable'))
  assert.ok(stepNodeSrc.includes('resolveDropPosition'))
  assert.ok(stepNodeSrc.includes('position: FlowNodeDropPosition'))
  assert.ok(stepNodeSrc.includes('context-menu'))
  assert.ok(src.includes('线性编译结果'))
  assert.ok(src.includes('应用到流程草稿'))
  assert.ok(src.includes('应用到预览'))
  assert.ok(src.includes('清除预览覆盖'))
  assert.ok(src.includes('hasVisualPreviewOverride'))
  assert.ok(src.includes('applyReadonlyFlowVisualToDraft'))
  assert.ok(src.includes('applyReadonlyFlowVisualToPreview'))
  assert.ok(src.includes('clearReadonlyFlowVisualPreviewOverride'))
  assert.ok(src.includes('visualPreviewOverrideSteps'))
  assert.ok(src.includes('buildPreviewFlowStepFromVisual'))
  assert.ok(src.includes('readonlyFlowCompileResult'))
  assert.ok(src.includes('addReadonlyFlowVisualStep'))
  assert.ok(src.includes('onReadonlyFlowVisualDragStart'))
  assert.ok(src.includes('onReadonlyFlowVisualDrop'))
  assert.ok(src.includes('reorderReadonlyFlowVisualNode'))
  assert.ok(src.includes('insertReadonlyFlowVisualStepNearNode'))
  assert.ok(src.includes('readonlyFlowRecentlyMovedNodeId'))
  assert.ok(src.includes('canReadonlyFlowVisualUndo'))
  assert.ok(src.includes('canReadonlyFlowVisualRedo'))
  assert.ok(src.includes('undoReadonlyFlowVisual'))
  assert.ok(src.includes('redoReadonlyFlowVisual'))
  assert.ok(src.includes('批量属性面板'))
  assert.ok(src.includes('readonlyFlowVisualBulkFields'))
  assert.ok(src.includes('applyReadonlyFlowVisualBulkPatch'))
  assert.ok(src.includes('onFlowVisualKeydown'))
  assert.ok(src.includes('setFlowVisualBodyScrollLocked'))
  assert.ok(src.includes('window.addEventListener(\'keydown\', onFlowVisualKeydown)'))
  assert.ok(src.includes('window.removeEventListener(\'keydown\', onFlowVisualKeydown)'))
  assert.ok(src.includes('flowVisualDraggingKind'))
  assert.ok(src.includes('patchReadonlyFlowVisualNode'))
  assert.ok(src.includes('readonlyFlowVisualPropertyFields'))
  assert.ok(src.includes('buildModuleDiffSummary'))
  assert.ok(src.includes('formatModuleDiffSummary'))
  assert.ok(src.includes('差异摘要'))
  assert.ok(compileSrc.includes('validateFlowVisualGraph'))
  assert.ok(compileSrc.includes('compileFlowVisualGraphToLinearSteps'))
  assert.ok(src.includes('buildListeningChoiceModuleFromLinearSteps'))
  assert.ok(mapperSrc.includes('buildListeningChoiceModuleFromLinearSteps'))
  assert.ok(mapperSrc.includes('ensureRequiredPerGroupSteps'))
  assert.ok(editableSrc.includes('reorderNodes'))
  assert.ok(editableSrc.includes('insertNodeNearTarget'))
  assert.ok(editableSrc.includes('recentlyMovedNodeId'))
  assert.ok(editableSrc.includes('canUndo'))
  assert.ok(editableSrc.includes('canRedo'))
  assert.ok(editableSrc.includes('undo()'))
  assert.ok(editableSrc.includes('redo()'))
  assert.ok(editableSrc.includes('pushHistorySnapshot'))
  assert.ok(typeSrc.includes('export interface FlowVisualNode'))
  assert.ok(typeSrc.includes('export interface FlowVisualGraph'))
})

test('flow center should keep routing diagnostics helpers in script layer', async () => {
  const src = await readFile('components/views/FlowModulesManager.vue')
  assert.ok(src.includes('flowProfileFixSuggestions'))
  assert.ok(src.includes('applyFlowProfileFixSuggestion'))
  assert.ok(src.includes('applyAllFlowProfileFixSuggestions'))
  assert.ok(!src.includes('自动修复建议'))
})

test('flow center should preview fix suggestions before applying changes', async () => {
  const src = await readFile('components/views/FlowModulesManager.vue')
  assert.ok(src.includes('修复预览'))
  assert.ok(src.includes('pendingFlowProfileFixSuggestions'))
  assert.ok(src.includes('openFlowProfileFixPreview'))
  assert.ok(src.includes('confirmFlowProfileFixPreview'))
})

test('flow center fix preview should show field-level before and after details', async () => {
  const src = await readFile('components/views/FlowModulesManager.vue')
  assert.ok(src.includes('previewFields'))
  assert.ok(src.includes('previewText'))
  assert.ok(src.includes('before: String(prevValue'))
  assert.ok(src.includes('after: String(nextValue'))
})

test('flow center should confirm before applying previewed fixes', async () => {
  const src = await readFile('components/views/FlowModulesManager.vue')
  assert.ok(src.includes("title: '确认应用修复预览'"))
  assert.ok(src.includes('uni.showModal'))
})

test('flow center should block route submissions when diagnostics fail', async () => {
  const src = await readFile('components/views/FlowModulesManager.vue')
  assert.ok(src.includes("title: '路由诊断未通过'"))
  assert.ok(src.includes('showFlowProfileSubmitBlocked'))
  assert.ok(src.includes('flowProfiles.upsertWithDiagnostics'))
  assert.ok(src.includes('flowProfiles.removeWithDiagnostics'))
})

test('flow center should validate listening-choice module before save', async () => {
  const src = await readFile('components/views/FlowModulesManager.vue')
  const lifecycleSrc = await readFile('components/views/flow-modules/useModuleLifecycle.ts')
  assert.ok(lifecycleSrc.includes('validateListeningChoiceStandardModule'))
  assert.ok(lifecycleSrc.includes("title: '题型流程校验失败'"))
  assert.ok(lifecycleSrc.includes("title: '题型流程校验提醒'"))
  assert.ok(src.includes('saveStandard(skipWarningCheck = false, skipImpactCheck = false, targetVersion?: number)'))
  assert.ok(src.includes('moduleLifecycle.saveStandard(skipWarningCheck, skipImpactCheck, targetVersion)'))
  assert.ok(lifecycleSrc.includes("title: '确认更新题型流程'"))
  assert.ok(lifecycleSrc.includes('命中路由规则'))
  assert.ok(lifecycleSrc.includes('受影响路由规则'))
})

test('flow center should use direct-update workflow for current flow line', async () => {
  const src = await readFile('components/views/FlowModulesManager.vue')
  const lifecycleSrc = await readFile('components/views/flow-modules/useModuleLifecycle.ts')
  assert.ok(src.includes('更新当前流程线'))
  assert.ok(src.includes('updateCurrentFlowLine'))
  assert.ok(!src.includes('另存新版本'))
  assert.ok(!src.includes('发布当前版本'))
  assert.ok(!src.includes('归档当前版本'))
  assert.ok(lifecycleSrc.includes("status: 'published'"))
  assert.ok(lifecycleSrc.includes('本模式默认直接覆盖更新，不保留历史版本'))
})

test('flow center should allow direct overwrite update in UI and save logic', async () => {
  const src = await readFile('components/views/FlowModulesManager.vue')
  const lifecycleSrc = await readFile('components/views/flow-modules/useModuleLifecycle.ts')
  assert.ok(src.includes('module-state'))
  assert.ok(src.includes('currentModuleStatus'))
  assert.ok(src.includes('canSaveCurrentStandard'))
  assert.ok(lifecycleSrc.includes('const canSaveCurrentStandard = computed(() => true)'))
  assert.ok(lifecycleSrc.includes("status: 'published'"))
  assert.ok(lifecycleSrc.includes("title: '确认更新题型流程'"))
})

test('flow center should allow editing module display name and note for save/publish', async () => {
  const src = await readFile('components/views/FlowModulesManager.vue')
  const lifecycleSrc = await readFile('components/views/flow-modules/useModuleLifecycle.ts')
  assert.ok(src.includes('流程名称'))
  assert.ok(src.includes('流程备注'))
  assert.ok(src.includes('draftModuleName'))
  assert.ok(src.includes('draftModuleNote'))
  assert.ok(lifecycleSrc.includes('const moduleName = normalizeModuleName(draftModuleName.value'))
  assert.ok(lifecycleSrc.includes('const moduleNote = normalizeModuleNote(draftModuleNote.value)'))
  assert.ok(lifecycleSrc.includes('name: moduleName'))
  assert.ok(lifecycleSrc.includes('note: moduleNote'))
})

test('flow center should show module names in region-binding targets', async () => {
  const src = await readFile('components/views/FlowModulesManager.vue')
  assert.ok(src.includes('function formatModuleDisplayRef('))
  assert.ok(src.includes('formatModuleDisplayRef(binding.module)'))
  assert.ok(src.includes('formatRegionBindingTarget'))
  assert.ok(src.includes('当前流程线：{{ draftModuleDisplayRef }}'))
})

test('listening-choice binding should skip archived module refs and fallback', async () => {
  const src = await readFile('engine/flow/listening-choice/binding.ts')
  assert.ok(src.includes('const isActiveModule = (module: ListeningChoiceFlowModuleV1 | null | undefined): module is ListeningChoiceFlowModuleV1 => {'))
  assert.ok(src.includes('if (isActiveModule(hit)) return { module: hit, profileId: profileId || undefined }'))
})

test('flow center should remove bulk profile-version migration compatibility actions', async () => {
  const src = await readFile('components/views/FlowModulesManager.vue')
  const lifecycleSrc = await readFile('components/views/flow-modules/useModuleLifecycle.ts')
  assert.ok(!src.includes('迁移到当前版本'))
  assert.ok(!src.includes('migrateFlowProfilesToCurrentVersion'))
  assert.ok(!lifecycleSrc.includes("title: '批量迁移路由版本'"))
  assert.ok(!lifecycleSrc.includes('migrateFlowProfilesToCurrentVersion'))
  assert.ok(!lifecycleSrc.includes('formatFlowProfileVersionSummary'))
})

test('flow center should remove batch old-version archive compatibility actions', async () => {
  const src = await readFile('components/views/FlowModulesManager.vue')
  const lifecycleSrc = await readFile('components/views/flow-modules/useModuleLifecycle.ts')
  assert.ok(!src.includes('批量归档旧版本'))
  assert.ok(!src.includes('archiveHistoricalStandards'))
  assert.ok(!lifecycleSrc.includes('flowModulesArchivableToCurrentVersion'))
  assert.ok(!lifecycleSrc.includes('archiveHistoricalStandards'))
  assert.ok(!lifecycleSrc.includes("title: '批量归档旧版本'"))
  assert.ok(!lifecycleSrc.includes('影响面预览'))
  assert.ok(!lifecycleSrc.includes("title: '仍有启用路由引用旧版本'"))
})

test('flow center should run template/module/profile cross-checks before module commit', async () => {
  const src = await readFile('components/views/FlowModulesManager.vue')
  const lifecycleSrc = await readFile('components/views/flow-modules/useModuleLifecycle.ts')
  const validatorSrc = await readFile('domain/flow-module/usecases/validateModuleCommitCrossChecks.ts')
  assert.ok(src.includes('validateModuleCommitBeforeSavePublish(payload: ModuleCommitValidationPayload)'))
  assert.ok(src.includes('validateListeningChoiceModuleCommitCrossChecks'))
  assert.ok(src.includes('validateBeforeCommit: validateModuleCommitBeforeSavePublish'))
  assert.ok(lifecycleSrc.includes('checkModuleCommitGuard'))
  assert.ok(lifecycleSrc.includes("title: '流程引用校验失败'"))
  assert.ok(validatorSrc.includes('template_groups_empty'))
  assert.ok(validatorSrc.includes('group_prepare_seconds_missing'))
  assert.ok(validatorSrc.includes('route_missing_module_ref'))
  assert.ok(validatorSrc.includes('route_archived_module_ref'))
  assert.ok(src.includes('flowVisualEditor.dirty.value'))
  assert.ok(src.includes('flow_visual_unapplied_changes'))
  assert.ok(src.includes("payload.mode === 'publish'"))
  assert.ok(src.includes('flow_visual_warning_'))
  assert.ok(src.includes('可视流程存在未应用变更'))
  assert.ok(lifecycleSrc.includes('commitMode: ModuleCommitMode = \'save\''))
  assert.ok(lifecycleSrc.includes('checkModuleCommitGuard(commitMode, draftPayload, targetRef)'))
  assert.ok(lifecycleSrc.includes("return saveStandard(skipWarningCheck, skipImpactCheck, undefined, 'publish')"))
})

test('flow visual editor should expose clearDirty for draft-apply workflow', async () => {
  const src = await readFile('components/views/flow-modules/useEditableFlowGraph.ts')
  assert.ok(src.includes('function clearDirty()'))
  assert.ok(src.includes('dirty.value = false'))
  assert.ok(src.includes('reloadFromQuestion,'))
  assert.ok(src.includes('clearDirty'))
})

test('applying visual flow to draft should clear stale blockers and resync visual baseline', async () => {
  const src = await readFile('components/views/FlowModulesManager.vue')
  const fnStart = src.indexOf('function applyReadonlyFlowVisualToDraft()')
  assert.ok(fnStart >= 0)
  const fnBody = src.slice(fnStart, fnStart + 4200)
  assert.ok(fnBody.includes('flowVisualEditor.clearDirty()'))
  assert.ok(fnBody.includes('clearCommitValidationIssues()'))
  assert.ok(fnBody.includes('flowVisualEditor.reloadFromQuestion()'))
})

test('flow center should provide field-level blocking issues with one-click jump for commit validation', async () => {
  const src = await readFile('components/views/FlowModulesManager.vue')
  const lifecycleSrc = await readFile('components/views/flow-modules/useModuleLifecycle.ts')
  const editorSrc = await readFile('components/editor/ListeningChoiceEditor.vue')

  assert.ok(src.includes('更新阻断项'))
  assert.ok(src.includes('jumpToCommitValidationIssue'))
  assert.ok(src.includes('jumpToFirstCommitValidationIssue'))
  assert.ok(src.includes("if (issue.scope === 'visual')"))
  assert.ok(src.includes("if (path.startsWith('flowVisual.')) return 'visual'"))
  assert.ok(src.includes("if (path.startsWith('flowProfiles')) return 'routing'"))
  assert.ok(src.includes('地区匹配 >'))
  assert.ok(src.includes(':focus-path="templateFocusPath"'))
  assert.ok(src.includes("onCommitValidationFailed: handleModuleCommitValidationFailed"))
  assert.ok(lifecycleSrc.includes('onCommitValidationFailed?: (result: ModuleCommitValidationResult) => boolean'))
  assert.ok(lifecycleSrc.includes('const handled = onCommitValidationFailed ? onCommitValidationFailed(result) : false'))
  assert.ok(editorSrc.includes('focusPath?: string'))
  assert.ok(editorSrc.includes('card--focused'))
  assert.ok(editorSrc.includes('sub-card--focused'))
})

test('flow engine should provide generic flow protocol and reducer abstractions for multi-question types', async () => {
  const typeSrc = await readFile('types/flow-engine.ts')
  assert.ok(typeSrc.includes('export interface FlowStepProtocol'))
  assert.ok(typeSrc.includes('export interface FlowModuleProtocol'))
  assert.ok(typeSrc.includes('export type FlowAutoNextSignal'))

  const runtimeSrc = await readFile('engine/flow/runtime.ts')
  assert.ok(runtimeSrc.includes('export function createFlowRuntimeState'))
  assert.ok(runtimeSrc.includes('export function reduceFlowRuntimeState'))

  const indexSrc = await readFile('engine/flow/index.ts')
  assert.ok(indexSrc.includes("export * from './runtime.ts'"))

  const listeningRuntimeSrc = await readFile('engine/flow/listening-choice/runtime.ts')
  assert.ok(listeningRuntimeSrc.includes('createFlowRuntimeState'))
  assert.ok(listeningRuntimeSrc.includes('reduceFlowRuntimeState'))
})

test('listening-choice renderer should read step-kind behavior from plugin registry', async () => {
  const pluginSrc = await readFile('components/renderer/listening-choice/stepPlugins.ts')
  assert.ok(pluginSrc.includes('STEP_BEHAVIOR_PLUGINS'))
  assert.ok(pluginSrc.includes('shouldReuseListeningChoicePreviousScreen'))
  assert.ok(pluginSrc.includes('resolveListeningChoiceStepAudioCarrier'))
  assert.ok(pluginSrc.includes('resolveListeningChoiceStepRenderView'))
  assert.ok(pluginSrc.includes('isListeningChoiceStepKind'))
  assert.ok(pluginSrc.includes('isListeningChoiceContextInfoStep'))

  const rendererSrc = await readFile('components/renderer/ListeningChoiceRenderer.vue')
  assert.ok(rendererSrc.includes("from './listening-choice/stepPlugins'"))
  assert.ok(rendererSrc.includes("import ListeningChoiceIntroBody from './listening-choice/ListeningChoiceIntroBody.vue'"))
  assert.ok(rendererSrc.includes("import ListeningChoicePlayAudioBody from './listening-choice/ListeningChoicePlayAudioBody.vue'"))
  assert.ok(rendererSrc.includes('const DISPLAY_RENDERERS'))
  assert.ok(rendererSrc.includes(':is="displayRenderer"'))
  assert.ok(rendererSrc.includes('displayRendererProps'))
  assert.ok(rendererSrc.includes('shouldReuseListeningChoicePreviousScreen(step)'))
  assert.ok(rendererSrc.includes('resolveListeningChoiceStepAudioCarrier(step)'))
  assert.ok(rendererSrc.includes('resolveListeningChoiceStepRenderView(displayStep.value)'))
  assert.ok(rendererSrc.includes('const activeStepRenderView = computed(() => resolveListeningChoiceStepRenderView(activeStep.value))'))
  assert.ok(rendererSrc.includes('const renderView = activeStepRenderView.value'))
})

test('speaking-steps renderer should use unified flow runtime reducer for step navigation', async () => {
  const runtimeSrc = await readFile('engine/flow/speaking-steps/runtime.ts')
  assert.ok(runtimeSrc.includes('createSpeakingStepsRuntimeState'))
  assert.ok(runtimeSrc.includes('reduceSpeakingStepsRuntimeState'))
  assert.ok(runtimeSrc.includes('reduceFlowRuntimeState'))

  const rendererSrc = await readFile('components/renderer/SpeakingStepsRenderer.vue')
  assert.ok(rendererSrc.includes("from '/engine/flow/speaking-steps/runtime.ts'"))
  assert.ok(rendererSrc.includes('dispatchRuntime({ type: \'next\' })'))
  assert.ok(rendererSrc.includes('dispatchRuntime({ type: \'prev\' })'))
})
