import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(__dirname, '..')

async function readFile(relPath) {
  return fs.readFile(path.join(repoRoot, relPath), 'utf8')
}

test('editable flow graph should provide history stack and undo/redo APIs', async () => {
  const src = await readFile('components/views/flow-modules/useEditableFlowGraph.ts')
  assert.ok(src.includes('historyPast'))
  assert.ok(src.includes('historyFuture'))
  assert.ok(src.includes('HISTORY_LIMIT'))
  assert.ok(src.includes('pushHistorySnapshot'))
  assert.ok(src.includes('canUndo'))
  assert.ok(src.includes('canRedo'))
  assert.ok(src.includes('function undo()'))
  assert.ok(src.includes('function redo()'))
  assert.ok(src.includes('function duplicateSelectedNode()'))
  assert.ok(src.includes('function validateStencilInsertion('))
  assert.ok(src.includes('answer_requires_play_audio'))
  assert.ok(src.includes('countdown_requires_prev_step'))
  assert.ok(src.includes('quickFixSuggestions'))
  assert.ok(src.includes('buildLinearFlowFixSuggestions'))
  assert.ok(src.includes('function applyQuickFixSuggestion(key: string)'))
  assert.ok(src.includes('snippetSelectionAnchorId'))
  assert.ok(src.includes('snippetSelectionNodeIds'))
  assert.ok(src.includes('function saveSnippetFromSelectionRange'))
  assert.ok(src.includes('function insertSnippetNearTarget'))
  assert.ok(src.includes('insertSnippetAtTail'))
  assert.ok(src.includes('selectPrevNode: () => selectAdjacentNode(-1)'))
  assert.ok(src.includes('selectNextNode: () => selectAdjacentNode(1)'))
  assert.ok(src.includes('linearConstraintChecks'))
})

test('editable flow graph should avoid no-op dirty marks and expose debug info', async () => {
  const src = await readFile('components/views/flow-modules/useEditableFlowGraph.ts')
  assert.ok(src.includes('if (!changed) return'))
  assert.ok(src.includes('markDirty('))
  assert.ok(src.includes('markClean('))
  assert.ok(src.includes('debugInfo'))
})

test('flow center should expose visual undo/redo buttons and keyboard shortcuts', async () => {
  const src = await readFile('components/views/FlowModulesManager.vue')
  const propertySrc = await readFile('components/editor/flow-visual/PropertyPanel.vue')
  const canvasSrc = await readFile('components/editor/flow-visual/ReadonlyFlowCanvas.vue')
  const stepNodeSrc = await readFile('components/editor/flow-visual/StepFlowNode.vue')
  assert.ok(src.includes('撤销'))
  assert.ok(src.includes('重做'))
  assert.ok(src.includes('canReadonlyFlowVisualUndo'))
  assert.ok(src.includes('canReadonlyFlowVisualRedo'))
  assert.ok(src.includes('undoReadonlyFlowVisual'))
  assert.ok(src.includes('redoReadonlyFlowVisual'))
  assert.ok(src.includes('if (!result.ok) {'))
  assert.ok(src.includes('uni.showToast({ title: result.message, icon: \'none\' })'))
  assert.ok(src.includes('readonlyFlowQuickFixSuggestions'))
  assert.ok(src.includes('一键修复建议'))
  assert.ok(src.includes('applyReadonlyFlowVisualQuickFix'))
  assert.ok(src.includes('流程片段'))
  assert.ok(src.includes('保存片段'))
  assert.ok(src.includes('applyReadonlyFlowVisualSnippet'))
  assert.ok(src.includes('saveReadonlyFlowVisualSnippet'))
  assert.ok(src.includes('setReadonlyFlowVisualSnippetAnchor'))
  assert.ok(propertySrc.includes('Ctrl/Cmd+Z'))
  assert.ok(src.includes("if (lower === 'z' && event.shiftKey)"))
  assert.ok(src.includes("if (lower === 'y')"))
  assert.ok(src.includes("if (lower === 'z')"))
  assert.ok(src.includes("if (lower === 'd')"))
  assert.ok(src.includes("if (event.key === 'ArrowUp')"))
  assert.ok(src.includes("if (event.key === 'ArrowDown')"))
  assert.ok(src.includes('readFlowVisualIssueNodeId'))
  assert.ok(src.includes('locateReadonlyFlowVisualIssue'))
  assert.ok(src.includes('readonlyFlowLinearChecks'))
  assert.ok(src.includes('readonlyFlowCompileResult.warnings.length'))
  assert.ok(src.includes('编译提醒'))
  assert.ok(src.includes('is-warning'))
  assert.ok(src.includes('flowVisualDebugInfo'))
  assert.ok(src.includes('最近动作'))
  assert.ok(propertySrc.includes('Ctrl/Cmd+D'))
  assert.ok(canvasSrc.includes('onPointerDragStart'))
  assert.ok(canvasSrc.includes('onPointerDragDrop'))
  assert.ok(stepNodeSrc.includes('pointer-drag-start'))
  assert.ok(stepNodeSrc.includes('onPointerDown'))
})
